import type { ReadTimeResults } from 'reading-time';
import type { Env as AutoGeneratedBindings } from './binding';

import {} from 'hono';

type Frontmatter = {
	title: string;
	navLabel?: string;
	publishedAt: string;
	ogpImage?: string;
	emoji: string;
	color: string;
	description?: string;
};

declare module 'hono' {
	interface Env {
		Bindings: AutoGeneratedBindings;
	}

	interface ContextRenderer {
		// biome-ignore lint/style/useShorthandFunctionType: <explanation>
		(
			content: string | Promise<string>,
			meta?: { frontmatter?: Frontmatter; readingTime?: ReadTimeResults },
		): Response | Promise<Response>;
	}
}

declare module '*.mdx' {
	export const readingTime: ReadTimeResults;
	export const frontmatter: Frontmatter;
}
